CatLabels = [
    "ggH 0J CEN",
    "ggH 0J FWD",
    "ggH 1J LOW",
    "ggH 1J MED",
    "ggH 1J HIGH",
    "ggH 1J BSM",
    "ggH 2J LOW",
    "ggH 2J MED",
    "ggH 2J HIGH",
    "ggH 2J BSM",
    "VBF loose, low p_{T}^{Hjj}",
    "VBF tight, low p_{T}^{Hjj}",
    "VBF loose, high p_{T}^{Hjj}",
    "VBF tight, high p_{T}^{Hjj}",
    "VH had loose",
    "VH had tight",
    "jet BSM",
    "VH MET LOW",
    "VH MET HIGH",
    "VH lep LOW",
    "VH lep HIGH",
    "VH dilep",
    "tH had 4j2b",
    "tH had 4j1b",
    "ttH had BDT4",
    "ttH had BDT3",
    "ttH had BDT2",
    "ttH had BDT1",
    "ttH lep",
    "tH lep 1fwd",
    "tH lep 0fwd"
]
